apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: sample-spring-boot-app-k8s-999
build:
  artifacts:
    - image: cnoe-demo/sample-spring-boot-app-k8s-999
      jib:
        args:
          - -Pjib
          - -DskipTests
manifests:
  rawYaml:
    - k8s/deployment.yaml
deploy:
  kubectl: {}